### ISSUE TITLE
Error running any blah command

### ISSUE THREAD

**Issue by grit96** [IonicaBizau/node-blah#20]
Running any blah command (`blah -r`, `blah -d index.js`, `blah -i`) returns the following error:
```
error Cannot find searched file: .gitignore
```
This happens in any repository with blah at version 2.0.0.

**Comment by IonicaBizau** [comment]
Hmm, that's weird... Can you please `console.log(tries)` [here](https://github.com/IonicaBizau/node-blah/blob/e97ecfa8bd191128893ea2762e4a1cd7201d19b8/lib/index.js#L92)?

**Comment by grit96** [comment]
```sh
$ blah -i

[ '/home/geraint/Downloads/repos/node/github-listener/.blah/docs.ejs',
  '/home/geraint/.blah-templates/docs.ejs',
  '/usr/lib/node_modules/blah/lib/templates/docs.ejs' ]
[ '/home/geraint/Downloads/repos/node/github-listener/.blah/README.ejs',
  '/home/geraint/.blah-templates/README.ejs',
  '/usr/lib/node_modules/blah/lib/templates/README.ejs' ]
[ '/home/geraint/Downloads/repos/node/github-listener/.blah/.gitignore',
  '/home/geraint/.blah-templates/.gitignore',
  '/usr/lib/node_modules/blah/lib/templates/.gitignore' ]
[ '/home/geraint/Downloads/repos/node/github-listener/.blah/CONTRIBUTING.ejs',
  '/home/geraint/.blah-templates/CONTRIBUTING.ejs',
  '/usr/lib/node_modules/blah/lib/templates/CONTRIBUTING.ejs' ]
error Cannot find searched file: .gitignore
```

**Comment by IonicaBizau** [comment]
Can you do a `ls /usr/lib/node_modules/blah/lib/templates/`? I think I've got it: `.gitignore` gets removed on [`npm publish`](https://github.com/npm/npm/issues/3763).

In the mean time you can do:

```sh
$ mkdir ~/.blah-templates
$ cd ~/.blah-templates
$ wget https://raw.githubusercontent.com/IonicaBizau/node-blah/master/lib/templates/.gitignore
```

This should fix the problem in your case. Obviously, this is a bug in this project. I think I will renamed the `.gitignore` file into another file.

**Comment by grit96** [comment]
Yes that's the problem, `.gitignore` is ignored by `npm publish` by default.

**Comment by IonicaBizau** [comment]
> The other option in the issue you linked is to create an empty .npmignore file.
Indeed, I will try that too!

**Comment by IonicaBizau** [comment]
@grit96 This should be fixed now. Install the latest version: `npm i -g blah@latest`. :tada: :ship: 2.1.0

**Comment by grit96** [comment]
@IonicaBizau Thanks, that seems to work now. :+1:

**Comment by IonicaBizau** [comment]
Cool! You're welcome! :apple:
