### ISSUE TITLE
No response on windows

### ISSUE THREAD

**Issue by 2dxgujun** [IonicaBizau/node-blah#22]
Win7 64
Node 0.12.7

**Comment by IonicaBizau** [comment]
Will test it soon into a virtual machine... Thanks for the report!

**Comment by IonicaBizau** [comment]
Reproduced! :bug:

**Comment by 2dxgujun** [comment]
Hi, i found it the problem:
```
ParentSearch(self.path, PACKAGE_JSON, cb);
```
when there is no *package.json* in the direction, it will enter an endless search.

I am a node beginner, i learning from your project :+1:

**Comment by IonicaBizau** [comment]
Oh, cool! :+1: 

Please [file an issue here](https://github.com/IonicaBizau/node-parent-search) and if you like, you can fix it. :smile: 

I suppose the issue is somewhere [here](https://github.com/IonicaBizau/node-parent-search/blob/be9ff759fba88d13d93d815993230dcb537788df/lib/index.js#L89-L98).

**Comment by IonicaBizau** [comment]
Probably it's Windows specific because I cannot reproduce it on Ubuntu. Maybe [this basepath expression](https://github.com/IonicaBizau/node-parent-search/blob/be9ff759fba88d13d93d815993230dcb537788df/lib/index.js#L90) is different on Windows?

**Comment by 2dxgujun** [comment]
Yes, it seems the file separator difference between Windows and Linux,  i will try to fix it :smile:

**Comment by IonicaBizau** [comment]
@2dxgujun Thanks! :sparkles:

**Comment by IonicaBizau** [comment]
@2dxgujun Can you please bump the version of `parent-search` and create a PR? :smile:

**Comment by 2dxgujun** [comment]
Yes, i will

**Comment by IonicaBizau** [comment]
Actually by running `npm i -g blah@latest`, you will get the correct version of `parent-search`. :star2: Enjoy! :sparkle:
